server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 1
      routes:
        - id: host_route
          uri: http://localhost:9999
          predicates:
            - Path=/scg/leak
      global-filter:
        remove-cached-body:
          enabled: false
        adapt-cached-body:
          enabled: false
        websocket-routing:
          enabled: false
        forward-path:
          enabled: false
        forward-routing:
          enabled: false

logging:
  level:
    reactor:
      netty: debug